#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: 371116543871-smkdnaq9u88v2a6e7lcf60q8igbva8ch.apps.googleusercontent.com
#            clientSecret: 1Uo94XCarrunIzKN4yAf_5JM
#            scope:
#              - email
#              - profile